import { Report, Organization, User, Notification, Comment, TimelineEntry, MapAnnouncement, BusinessSponsor } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Alisher Nazarov',
    email: 'alisher@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alisher&backgroundColor=b6e3f4',
    role: 'citizen',
    phone: '+998 90 123-45-67',
    district: 'Yunusobod',
    createdAt: '2024-01-15T10:00:00Z',
    reportsCount: 12,
    votesCount: 45,
    isVerified: true,
    bio: "Toshkent fuqarosi. Shaharni yaxshilashda faol ishtirok etaman.",
  },
  {
    id: 'user-2',
    name: 'Malika Yusupova',
    email: 'malika@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=malika&backgroundColor=ffdfbf',
    role: 'citizen',
    phone: '+998 91 234-56-78',
    district: 'Chilonzor',
    createdAt: '2024-02-20T09:00:00Z',
    reportsCount: 8,
    votesCount: 67,
    isVerified: false,
  },
  {
    id: 'user-3',
    name: 'Sherzod Toshmatov',
    email: 'sherzod@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sherzod&backgroundColor=c0aede',
    role: 'citizen',
    phone: '+998 93 345-67-89',
    district: "Mirzo Ulug'bek",
    createdAt: '2024-03-05T08:00:00Z',
    reportsCount: 5,
    votesCount: 23,
    isVerified: false,
  },
  {
    id: 'user-org',
    name: 'Bobur Karimov',
    email: 'bobur@roads.toshkent.uz',
    role: 'organization',
    district: 'Yunusobod',
    createdAt: '2023-11-10T07:00:00Z',
    reportsCount: 0,
    votesCount: 12,
    isVerified: true,
  },
  {
    id: 'user-admin',
    name: 'Admin OpenCity',
    email: 'admin@opencity.uz',
    role: 'admin',
    district: 'Toshkent',
    createdAt: '2023-01-01T00:00:00Z',
    reportsCount: 0,
    votesCount: 0,
    isVerified: true,
  },
];

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-roads',
    name: "Toshkent Yo'l Boshqarmasi",
    description: "Toshkent shahridagi barcha ko'cha va yo'llarni ta'mirlash, qurish va boshqarish. Ko'priklar, tunnellar va yo'l infratuzilmasi.",
    categoryIds: ['roads'],
    phone: '+998 71 200-00-01',
    email: 'roads@toshkent.uz',
    website: 'https://roads.toshkent.uz',
    verified: true,
    completedReports: 234,
    activeReports: 18,
    avgResponseTime: '3 kun',
    rating: 4.2,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 252,
  },
  {
    id: 'org-electricity',
    name: "Toshkent Elektr Tarmog'i",
    description: "Elektr ta'minoti, ko'cha chiroqlari, transformatorlar va elektr infratuzilmasini boshqarish.",
    categoryIds: ['electricity', 'streetlights'],
    phone: '+998 71 200-00-02',
    email: 'electric@toshkent.uz',
    website: 'https://tashkentenergo.uz',
    verified: true,
    completedReports: 456,
    activeReports: 32,
    avgResponseTime: '1.5 kun',
    rating: 4.6,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 488,
  },
  {
    id: 'org-water',
    name: 'Toshkent Suvokova',
    description: "Ichimlik suvi ta'minoti, kanalizatsiya tizimlarini ta'mirlash va qurish.",
    categoryIds: ['water', 'sewage'],
    phone: '+998 71 200-00-03',
    email: 'water@toshkent.uz',
    website: 'https://suvokova.uz',
    verified: true,
    completedReports: 389,
    activeReports: 24,
    avgResponseTime: '2 kun',
    rating: 4.1,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 413,
  },
  {
    id: 'org-gas',
    name: 'Toshkentgaz',
    description: "Gaz ta'minoti, gaz quvurlari va gaz qurilmalarini xavfsiz boshqarish.",
    categoryIds: ['gas'],
    phone: '+998 71 200-00-04',
    email: 'gas@toshkentgaz.uz',
    website: 'https://toshkentgaz.uz',
    verified: true,
    completedReports: 178,
    activeReports: 8,
    avgResponseTime: '4 soat',
    rating: 4.8,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 186,
  },
  {
    id: 'org-sanitation',
    name: 'Toshkent Sanitariya',
    description: "Axlat yig'ish, ko'cha tozalash va sanitariya-gigiena xizmatlarini ko'rsatish.",
    categoryIds: ['garbage'],
    phone: '+998 71 200-00-05',
    email: 'clean@toshkent.uz',
    verified: true,
    completedReports: 567,
    activeReports: 45,
    avgResponseTime: '1 kun',
    rating: 3.9,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 612,
  },
  {
    id: 'org-landscaping',
    name: 'Toshkent Obodonlashtirish',
    description: "Shahar parklarini, daraxtlarini va ko'k maydonlarini parvarish qilish va obodonlashtirish.",
    categoryIds: ['parks', 'trees'],
    phone: '+998 71 200-00-06',
    email: 'green@toshkent.uz',
    verified: true,
    completedReports: 123,
    activeReports: 15,
    avgResponseTime: '5 kun',
    rating: 4.0,
    district: 'Toshkent',
    joinedAt: '2023-02-01T00:00:00Z',
    totalReports: 138,
  },
  {
    id: 'org-transport',
    name: 'Toshkent Shahar Transport',
    description: "Jamoat transporti marshrutlari, avtobus to'xtamashlari va transport infratuzilmasini boshqarish.",
    categoryIds: ['transport'],
    phone: '+998 71 200-00-07',
    email: 'transport@toshkent.uz',
    verified: true,
    completedReports: 89,
    activeReports: 12,
    avgResponseTime: '3 kun',
    rating: 3.7,
    district: 'Toshkent',
    joinedAt: '2023-03-01T00:00:00Z',
    totalReports: 101,
  },
  {
    id: 'org-environment',
    name: 'Toshkent Ekologiya',
    description: "Atrof-muhit muhofazasi, hayvonlar va ekologik muammolarni hal qilish.",
    categoryIds: ['environment', 'animals'],
    phone: '+998 71 200-00-08',
    email: 'eco@toshkent.uz',
    verified: true,
    completedReports: 67,
    activeReports: 9,
    avgResponseTime: '4 kun',
    rating: 4.3,
    district: 'Toshkent',
    joinedAt: '2023-02-15T00:00:00Z',
    totalReports: 76,
  },
  {
    id: 'org-construction',
    name: 'Toshkent Shaharsozlik',
    description: "Binolar, imoratlar xavfsizligini nazorat qilish va qurilish muammolarini hal etish.",
    categoryIds: ['buildings'],
    phone: '+998 71 200-00-09',
    email: 'build@toshkent.uz',
    verified: true,
    completedReports: 45,
    activeReports: 6,
    avgResponseTime: '7 kun',
    rating: 3.8,
    district: 'Toshkent',
    joinedAt: '2023-04-01T00:00:00Z',
    totalReports: 51,
  },
  {
    id: 'org-police',
    name: "Toshkent IIB",
    description: "Shahar xavfsizligi, tartib-intizomni ta'minlash va jinoyatchilikka qarshi kurash.",
    categoryIds: ['safety'],
    phone: '+998 71 200-00-10',
    email: 'police@iib.uz',
    website: 'https://iib.uz',
    verified: true,
    completedReports: 156,
    activeReports: 18,
    avgResponseTime: '2 soat',
    rating: 4.5,
    district: 'Toshkent',
    joinedAt: '2023-01-15T00:00:00Z',
    totalReports: 174,
  },
  {
    id: 'org-admin',
    name: "Toshkent Shahar Ma'muriyati",
    description: "Boshqa turli muammolarni koordinatsiya qilish va hal etishda ko'maklashish.",
    categoryIds: ['other'],
    phone: '+998 71 200-00-11',
    email: 'admin@tashkent.uz',
    website: 'https://tashkent.uz',
    verified: true,
    completedReports: 234,
    activeReports: 21,
    avgResponseTime: '5 kun',
    rating: 3.6,
    district: 'Toshkent',
    joinedAt: '2023-01-01T00:00:00Z',
    totalReports: 255,
  },
];

const makeTimeline = (entries: Partial<TimelineEntry>[]): TimelineEntry[] =>
  entries.map((e, i) => ({
    id: `tl-${i}`,
    status: e.status || 'new',
    note: e.note || '',
    authorId: e.authorId || 'user-1',
    authorName: e.authorName || 'Alisher Nazarov',
    authorRole: e.authorRole || 'citizen',
    organizationName: e.organizationName,
    createdAt: e.createdAt || new Date().toISOString(),
  }));

const makeComment = (c: Partial<Comment>): Comment => ({
  id: `cmt-${Math.random().toString(36).substr(2, 6)}`,
  reportId: c.reportId || '',
  authorId: c.authorId || 'user-1',
  authorName: c.authorName || 'Alisher',
  authorAvatar: c.authorAvatar,
  authorRole: c.authorRole || 'citizen',
  text: c.text || '',
  images: c.images,
  likes: c.likes || 0,
  parentId: c.parentId,
  replies: c.replies,
  createdAt: c.createdAt || new Date().toISOString(),
  isLiked: false,
});

export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-001',
    title: "Yunusobod ko'chasida katta chuqur",
    description: "Mirzo Ulug'bek ko'chasining Yunusobod tumani qismida katta chuqur paydo bo'lgan. Mashinalar shikastlanmoqda, piyodalar uchun ham xavfli. Bir hafta bo'ldi, hech kim tuzatmayapti.",
    categoryId: 'roads',
    status: 'inprogress',
    location: { lat: 41.352, lng: 69.291, address: "Mirzo Ulug'bek ko'chasi, 45", district: 'Yunusobod' },
    photos: [
      'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&fit=crop',
      'https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=800&fit=crop',
    ],
    authorId: 'user-1',
    authorName: 'Alisher Nazarov',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alisher',
    anonymous: false,
    organizationId: 'org-roads',
    votes: 87,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-001', authorId: 'user-2', authorName: 'Malika Yusupova', authorRole: 'citizen', text: "Ha, men ham shu yo'ldan o'taman, juda xavfli. Tezroq hal qilish kerak!", likes: 12, createdAt: '2025-07-22T10:00:00Z' }),
      makeComment({ reportId: 'rep-001', authorId: 'user-org', authorName: "Yo'l Boshqarmasi", authorRole: 'organization', text: "Muammo ro'yxatga olingan. Usta brigada 3 kun ichida keladi.", likes: 8, createdAt: '2025-07-22T14:00:00Z' }),
    ],
    createdAt: '2025-07-20T08:00:00Z',
    updatedAt: '2025-07-22T14:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Alisher Nazarov', authorRole: 'citizen', createdAt: '2025-07-20T08:00:00Z' },
      { status: 'review', note: "Ko'rib chiqilmoqda", authorName: "Yo'l Boshqarmasi", authorRole: 'organization', organizationName: "Yo'l Boshqarmasi", createdAt: '2025-07-21T09:00:00Z' },
      { status: 'inprogress', note: 'Ish boshlandi, 3 kun ichida tugallanadi', authorName: "Yo'l Boshqarmasi", authorRole: 'organization', organizationName: "Yo'l Boshqarmasi", createdAt: '2025-07-22T14:00:00Z' },
    ]),
    priority: 'high',
    viewCount: 342,
  },
  {
    id: 'rep-002',
    title: "Ko'cha chirog'i 2 haftadan beri ishlamayapti",
    description: "Chilonzor tumani, Bunyodkor ko'chasidagi 3 ta ko'cha chirog'i ishlamayapti. Kechasi juda qorong'i va xavfli. Bolalar maktabdan qaytadi bu yo'l orqali.",
    categoryId: 'streetlights',
    status: 'completed',
    location: { lat: 41.273, lng: 69.197, address: "Bunyodkor ko'chasi, 12", district: 'Chilonzor' },
    photos: ['https://images.unsplash.com/photo-1547516994-8f54b9e59a12?w=800&fit=crop'],
    authorId: 'user-2',
    authorName: 'Malika Yusupova',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=malika',
    anonymous: false,
    organizationId: 'org-electricity',
    votes: 43,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-002', authorId: 'user-3', authorName: 'Sherzod T.', authorRole: 'citizen', text: "Rahmat! Nihoyat yoritildi.", likes: 5, createdAt: '2025-07-18T11:00:00Z' }),
    ],
    createdAt: '2025-07-10T07:00:00Z',
    updatedAt: '2025-07-18T10:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Malika Yusupova', authorRole: 'citizen', createdAt: '2025-07-10T07:00:00Z' },
      { status: 'accepted', note: 'Qabul qilindi', authorName: "Elektr Tarmog'i", authorRole: 'organization', createdAt: '2025-07-11T09:00:00Z' },
      { status: 'inprogress', note: 'Elektrik mutaxassis yuborildi', authorName: "Elektr Tarmog'i", authorRole: 'organization', createdAt: '2025-07-15T10:00:00Z' },
      { status: 'completed', note: 'Barcha 3 ta chiroq ta\'mirlandi va ishga tushirildi', authorName: "Elektr Tarmog'i", authorRole: 'organization', createdAt: '2025-07-18T10:00:00Z' },
    ]),
    completionPhotos: ['https://images.unsplash.com/photo-1565967511849-76a60a516170?w=800&fit=crop'],
    completionDescription: 'Barcha 3 ta ko\'cha chirog\'i yangi LED lampalar bilan almashtirildi.',
    completionDate: '2025-07-18T10:00:00Z',
    solvedBy: "Toshkent Elektr Tarmog'i",
    priority: 'medium',
    viewCount: 156,
  },
  {
    id: 'rep-003',
    title: 'Gaz hidi kelmoqda — SHOSHILINCH',
    description: "Olmazar tumani, Qoratosh ko'chasida kuchli gaz hidi sezilmoqda. Qo'shnilar ham his qilishmoqda. Portlash xavfi bor! Tezda kelinglar!",
    categoryId: 'gas',
    status: 'inprogress',
    location: { lat: 41.316, lng: 69.256, address: "Qoratosh ko'chasi, 8", district: 'Olmazar' },
    photos: [],
    authorId: 'user-3',
    authorName: 'Sherzod Toshmatov',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sherzod',
    anonymous: false,
    organizationId: 'org-gas',
    votes: 167,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-003', authorId: 'user-org', authorName: 'Toshkentgaz', authorRole: 'organization', text: 'Mutaxassislarimiz yo\'lda! 30 daqiqada boramiz. Iltimos, deraza-eshiklarni oching va olov yoqmang.', likes: 34, createdAt: '2025-07-23T09:15:00Z' }),
    ],
    createdAt: '2025-07-23T09:00:00Z',
    updatedAt: '2025-07-23T09:30:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Shoshilinch muammo bildirilib, tizimga qo\'shildi', authorName: 'Sherzod Toshmatov', authorRole: 'citizen', createdAt: '2025-07-23T09:00:00Z' },
      { status: 'inprogress', note: 'Mutaxassislar yuborildi — SHOSHILINCH', authorName: 'Toshkentgaz', authorRole: 'organization', createdAt: '2025-07-23T09:10:00Z' },
    ]),
    priority: 'urgent',
    viewCount: 892,
  },
  {
    id: 'rep-004',
    title: 'Suv quvuri yorildi, ko\'cha suv ostida',
    description: "Mirzo Ulug'bek tumani, Universitet ko'chasida asosiy suv quvuri yorilgan. Suv ko'chaga oqmoqda, mashina va piyodalar o'ta olmayapti.",
    categoryId: 'water',
    status: 'completed',
    location: { lat: 41.322, lng: 69.312, address: "Universitet ko'chasi, 27", district: "Mirzo Ulug'bek" },
    photos: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&fit=crop',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&fit=crop',
    ],
    authorId: 'user-1',
    authorName: 'Alisher Nazarov',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alisher',
    anonymous: false,
    organizationId: 'org-water',
    votes: 92,
    isVoted: true,
    comments: [],
    createdAt: '2025-07-15T06:00:00Z',
    updatedAt: '2025-07-17T16:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Alisher Nazarov', authorRole: 'citizen', createdAt: '2025-07-15T06:00:00Z' },
      { status: 'review', note: 'Ko\'rib chiqilmoqda', authorName: 'Toshkent Suvokova', authorRole: 'organization', createdAt: '2025-07-15T07:30:00Z' },
      { status: 'inprogress', note: 'Suvokova brigada yuborildi', authorName: 'Toshkent Suvokova', authorRole: 'organization', createdAt: '2025-07-15T10:00:00Z' },
      { status: 'completed', note: 'Quvur ta\'mirlandi, suv to\'xtatildi', authorName: 'Toshkent Suvokova', authorRole: 'organization', createdAt: '2025-07-17T16:00:00Z' },
    ]),
    completionPhotos: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&fit=crop'],
    completionDescription: 'Asosiy suv quvurining 2 metrlik bo\'lagi almashtirildi.',
    completionDate: '2025-07-17T16:00:00Z',
    solvedBy: 'Toshkent Suvokova',
    priority: 'urgent',
    viewCount: 445,
  },
  {
    id: 'rep-005',
    title: 'Axlat 1 haftadan beri yig\'ilmagan',
    description: "Yakkasaroy tumani, Bobur ko'chasida axlat konteynerlar to'lib toshgan. Yoqimsiz hid va sanitariya muammosi bor. Bolalar bog'chasi yonida!",
    categoryId: 'garbage',
    status: 'review',
    location: { lat: 41.291, lng: 69.218, address: "Bobur ko'chasi, 31", district: 'Yakkasaroy' },
    photos: ['https://images.unsplash.com/photo-1605600659908-0ef719419d41?w=800&fit=crop'],
    authorId: 'user-2',
    authorName: 'Malika Yusupova',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=malika',
    anonymous: false,
    organizationId: 'org-sanitation',
    votes: 38,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-005', authorId: 'user-1', authorName: 'Alisher N.', authorRole: 'citizen', text: "Bir hafta bo'ldi! Sanitariya xizmati nima qilyapti?", likes: 15, createdAt: '2025-07-21T12:00:00Z' }),
    ],
    createdAt: '2025-07-18T09:00:00Z',
    updatedAt: '2025-07-21T11:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Malika Yusupova', authorRole: 'citizen', createdAt: '2025-07-18T09:00:00Z' },
      { status: 'review', note: 'Ko\'rib chiqilmoqda', authorName: 'Toshkent Sanitariya', authorRole: 'organization', createdAt: '2025-07-21T11:00:00Z' },
    ]),
    priority: 'high',
    viewCount: 178,
  },
  {
    id: 'rep-006',
    title: "Park skameykasi singan va xavfli",
    description: "Shayxontohur tumani, Navro'z parki yonida skameyka to'liq singan. Bolalar o'tirsa yaralanishi mumkin. Tezda almashtirish kerak.",
    categoryId: 'parks',
    status: 'new',
    location: { lat: 41.301, lng: 69.243, address: "Navro'z parki, Shayxontohur", district: 'Shayxontohur' },
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&fit=crop'],
    authorId: 'user-3',
    authorName: 'Sherzod Toshmatov',
    anonymous: false,
    organizationId: 'org-landscaping',
    votes: 15,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-23T07:30:00Z',
    updatedAt: '2025-07-23T07:30:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Sherzod Toshmatov', authorRole: 'citizen', createdAt: '2025-07-23T07:30:00Z' },
    ]),
    priority: 'medium',
    viewCount: 45,
    sponsors: [
      {
        id: 'spon-001',
        reportId: 'rep-006',
        businessName: 'Comfort Mebel UZ',
        businessDescription: "Park va ko'cha uskunalari ishlab chiqarish",
        website: 'https://comfort-mebel.uz',
        pledgeMessage: "5 ta yangi metaldan qilingan park skameykasini bepul o'rnatamiz. Kompaniyamiz nomi yozilgan bo'ladi.",
        sponsorType: 'full' as const,
        status: 'pledged' as const,
        pledgedAt: '2025-07-23T12:00:00Z',
      },
      {
        id: 'spon-002',
        reportId: 'rep-006',
        businessName: 'ArtLine Dizayn',
        businessDescription: 'Shahar muhiti bezatish va dizayn studiyasi',
        pledgeMessage: "Yangi skameykalar uchun bepul dizayn va bo'yoq ishlarini bajaramiz.",
        sponsorType: 'material' as const,
        status: 'pledged' as const,
        pledgedAt: '2025-07-23T14:30:00Z',
      },
    ] as BusinessSponsor[],
  },
  {
    id: 'rep-007',
    title: "Daraxt yiqilish xavfi bor",
    description: "Yunusobod tumani, Amir Temur xiyobonida katta daraxt chirigan va yiqilish xavfi bor. Dovul bo'lganda odamlar shikastlanishi mumkin.",
    categoryId: 'trees',
    status: 'inprogress',
    location: { lat: 41.296, lng: 69.281, address: 'Amir Temur xiyoboni, 18', district: 'Yunusobod' },
    photos: ['https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=800&fit=crop'],
    authorId: 'user-1',
    authorName: 'Alisher Nazarov',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alisher',
    anonymous: false,
    organizationId: 'org-landscaping',
    votes: 71,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-007', authorId: 'user-org', authorName: 'Obodonlashtirish', authorRole: 'organization', text: "Arborist keldi va tekshirdi. Daraxtni kesish rejalashtirildi.", likes: 9, createdAt: '2025-07-22T13:00:00Z' }),
    ],
    createdAt: '2025-07-19T11:00:00Z',
    updatedAt: '2025-07-22T13:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Alisher Nazarov', authorRole: 'citizen', createdAt: '2025-07-19T11:00:00Z' },
      { status: 'review', note: 'Ko\'rib chiqilmoqda', authorName: 'Toshkent Obodonlashtirish', authorRole: 'organization', createdAt: '2025-07-20T10:00:00Z' },
      { status: 'inprogress', note: 'Arborist tekshirdi, kesish rejalashtirildi', authorName: 'Toshkent Obodonlashtirish', authorRole: 'organization', createdAt: '2025-07-22T13:00:00Z' },
    ]),
    priority: 'high',
    viewCount: 234,
    sponsors: [
      {
        id: 'spon-003',
        reportId: 'rep-007',
        businessName: 'GreenCity Landscaping',
        businessDescription: "Professional arboristika va ko'kalamzorlashtirish xizmatlari",
        website: 'https://greencity.uz',
        contactEmail: 'info@greencity.uz',
        contactPhone: '+998 90 500-10-20',
        pledgeMessage: "Daraxtni xavfsiz kesib, o'rniga ikki yangi yosh daraxt ekamiz. Barcha xarajatlar va ish kuchi kompaniyamizdan.",
        sponsorType: 'full' as const,
        status: 'in_progress' as const,
        pledgedAt: '2025-07-20T10:00:00Z',
      },
    ] as BusinessSponsor[],
  },
  {
    id: 'rep-008',
    title: "Yo'l chizig'i ko'rinmayapti",
    description: "Mirzo Ulug'bek — Yunusobod yo'lida piyodalar o'tish joyidagi chiziqlar butunlay o'chib ketgan. Avtomobillar to'xtamayapti.",
    categoryId: 'roads',
    status: 'accepted',
    location: { lat: 41.306, lng: 69.273, address: "Mirzo Ulug'bek ko'chasi, 67", district: 'Yunusobod' },
    photos: ['https://images.unsplash.com/photo-1568609586816-4f28f0804ad2?w=800&fit=crop'],
    authorId: 'user-2',
    authorName: 'Malika Yusupova',
    anonymous: false,
    organizationId: 'org-roads',
    votes: 29,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-17T08:00:00Z',
    updatedAt: '2025-07-20T09:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Malika Yusupova', authorRole: 'citizen', createdAt: '2025-07-17T08:00:00Z' },
      { status: 'review', note: 'Ko\'rib chiqilmoqda', authorName: "Yo'l Boshqarmasi", authorRole: 'organization', createdAt: '2025-07-18T10:00:00Z' },
      { status: 'accepted', note: 'Navbatchi belgilandi, oyning oxirida bajariladi', authorName: "Yo'l Boshqarmasi", authorRole: 'organization', createdAt: '2025-07-20T09:00:00Z' },
    ]),
    priority: 'medium',
    viewCount: 123,
  },
  {
    id: 'rep-009',
    title: "Ko'prikda teshik, xavfli",
    description: "Olmazar tumani, Beshyog'och ko'prigida asfalt qoplamasi teshilgan. Velosiped va mototsikllar uchun juda xavfli.",
    categoryId: 'roads',
    status: 'new',
    location: { lat: 41.336, lng: 69.252, address: 'Beshyog\'och ko\'prigi', district: 'Olmazar' },
    photos: ['https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&fit=crop'],
    authorId: 'user-3',
    authorName: 'Sherzod Toshmatov',
    anonymous: true,
    organizationId: 'org-roads',
    votes: 82,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-22T15:00:00Z',
    updatedAt: '2025-07-22T15:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Noma\'lum foydalanuvchi', authorRole: 'citizen', createdAt: '2025-07-22T15:00:00Z' },
    ]),
    priority: 'urgent',
    viewCount: 267,
  },
  {
    id: 'rep-010',
    title: "Bino devori yiqilish xavfi",
    description: "Yakkasaroy tumani, 5-uy binosi devori yorilgan va yiqilish xavfi bor. Yonida bolalar o'ynaydi. Darhol tekshirilsin!",
    categoryId: 'buildings',
    status: 'review',
    location: { lat: 41.288, lng: 69.228, address: "Ko'yliq ko'chasi, 5-uy", district: 'Yakkasaroy' },
    photos: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&fit=crop'],
    authorId: 'user-1',
    authorName: 'Alisher Nazarov',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alisher',
    anonymous: false,
    organizationId: 'org-construction',
    votes: 96,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-010', authorId: 'user-2', authorName: 'Malika Y.', authorRole: 'citizen', text: 'Juda xavfli! Shaharsozlik zudlik bilan tekshirishi kerak.', likes: 22, createdAt: '2025-07-23T08:00:00Z' }),
    ],
    createdAt: '2025-07-23T06:00:00Z',
    updatedAt: '2025-07-23T10:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Alisher Nazarov', authorRole: 'citizen', createdAt: '2025-07-23T06:00:00Z' },
      { status: 'review', note: 'Qurilish inspektori yuborildi', authorName: 'Toshkent Shaharsozlik', authorRole: 'organization', createdAt: '2025-07-23T10:00:00Z' },
    ]),
    priority: 'urgent',
    viewCount: 534,
  },
  {
    id: 'rep-011',
    title: "Elektr simlari yalang'och va xavfli",
    description: "Mirzo Ulug'bek tumani, Zarqaynar ko'chasida elektr simlari yalang'och qolgan. Yomg'irda tok urishi mumkin!",
    categoryId: 'electricity',
    status: 'review',
    location: { lat: 41.311, lng: 69.296, address: "Zarqaynar ko'chasi, 14", district: "Mirzo Ulug'bek" },
    photos: [],
    authorId: 'user-3',
    authorName: 'Sherzod Toshmatov',
    anonymous: false,
    organizationId: 'org-electricity',
    votes: 114,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-21T14:00:00Z',
    updatedAt: '2025-07-22T09:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Sherzod Toshmatov', authorRole: 'citizen', createdAt: '2025-07-21T14:00:00Z' },
      { status: 'review', note: 'Elektrik bo\'lim ko\'rib chiqmoqda', authorName: "Elektr Tarmog'i", authorRole: 'organization', createdAt: '2025-07-22T09:00:00Z' },
    ]),
    priority: 'urgent',
    viewCount: 389,
  },
  {
    id: 'rep-012',
    title: "Avtobus to'xtamasi singan",
    description: "Chilonzor tumani, 34-avtobus to'xtamasi to'liq singan, tom yo'q, skameyka yo'q. Yomg'irda odamlar turishga joy yo'q.",
    categoryId: 'transport',
    status: 'new',
    location: { lat: 41.281, lng: 69.201, address: "Chilonzor 34-kvart, 34-bekat", district: 'Chilonzor' },
    photos: ['https://images.unsplash.com/photo-1570464197285-9949814674a7?w=800&fit=crop'],
    authorId: 'user-2',
    authorName: 'Malika Yusupova',
    anonymous: false,
    organizationId: 'org-transport',
    votes: 24,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-23T10:00:00Z',
    updatedAt: '2025-07-23T10:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Malika Yusupova', authorRole: 'citizen', createdAt: '2025-07-23T10:00:00Z' },
    ]),
    priority: 'medium',
    viewCount: 67,
  },
  {
    id: 'rep-013',
    title: "Ko'cha iti mahallani bezovta qilmoqda",
    description: "Shayxontohur tumani, Sebzor ko'chasida bir nechta ko'cha iti odamlarni quvlayapti. Bolalar va keksalar uchun xavfli.",
    categoryId: 'animals',
    status: 'new',
    location: { lat: 41.298, lng: 69.237, address: "Sebzor ko'chasi, 22", district: 'Shayxontohur' },
    photos: [],
    authorId: 'user-1',
    authorName: 'Alisher Nazarov',
    anonymous: false,
    organizationId: 'org-environment',
    votes: 19,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-23T11:00:00Z',
    updatedAt: '2025-07-23T11:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Alisher Nazarov', authorRole: 'citizen', createdAt: '2025-07-23T11:00:00Z' },
    ]),
    priority: 'high',
    viewCount: 78,
  },
  {
    id: 'rep-014',
    title: "Kanalizatsiya tiqilib qoldi",
    description: "Sergeli tumani, Yangi hayot ko'chasida kanalizatsiya to'siq. Hid juda yoqimsiz, suv ko'chaga chiqmoqda.",
    categoryId: 'sewage',
    status: 'inprogress',
    location: { lat: 41.235, lng: 69.215, address: "Yangi hayot ko'chasi, 7", district: 'Sergeli' },
    photos: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&fit=crop'],
    authorId: 'user-3',
    authorName: 'Sherzod Toshmatov',
    anonymous: false,
    organizationId: 'org-water',
    votes: 56,
    isVoted: false,
    comments: [],
    createdAt: '2025-07-20T13:00:00Z',
    updatedAt: '2025-07-22T11:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Sherzod Toshmatov', authorRole: 'citizen', createdAt: '2025-07-20T13:00:00Z' },
      { status: 'inprogress', note: 'Suvokova mutaxassislari yuborildi', authorName: 'Toshkent Suvokova', authorRole: 'organization', createdAt: '2025-07-22T11:00:00Z' },
    ]),
    priority: 'high',
    viewCount: 145,
  },
  {
    id: 'rep-015',
    title: "Chiqindi qutisi yo'q",
    description: "Yunusobod tumani, Sharaf Rashidov ko'chasida chiqindi qutisi umuman yo'q. Odamlar axlatni yerga tashlashga majbur.",
    categoryId: 'garbage',
    status: 'rejected',
    location: { lat: 41.341, lng: 69.285, address: "Sharaf Rashidov ko'chasi, 99", district: 'Yunusobod' },
    photos: [],
    authorId: 'user-2',
    authorName: 'Malika Yusupova',
    anonymous: false,
    organizationId: 'org-sanitation',
    votes: 11,
    isVoted: false,
    comments: [
      makeComment({ reportId: 'rep-015', authorId: 'user-org', authorName: 'Toshkent Sanitariya', authorRole: 'organization', text: "Ushbu ko'chada yangi chiqindi qutilari o'rnatish uchun tuman hokimligidan ruxsat kerak. Hujjatlar tayyorlanmoqda.", likes: 3, createdAt: '2025-07-19T15:00:00Z' }),
    ],
    createdAt: '2025-07-16T10:00:00Z',
    updatedAt: '2025-07-19T15:00:00Z',
    timeline: makeTimeline([
      { status: 'new', note: 'Muammo bildirilib, tizimga qo\'shildi', authorName: 'Malika Yusupova', authorRole: 'citizen', createdAt: '2025-07-16T10:00:00Z' },
      { status: 'rejected', note: "Ushbu so'rov tuman hokimligiga yo'naltirildi", authorName: 'Toshkent Sanitariya', authorRole: 'organization', createdAt: '2025-07-19T15:00:00Z' },
    ]),
    priority: 'low',
    viewCount: 89,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    type: 'status_change',
    title: 'Muammo holati yangilandi',
    message: "Yunusobod ko'chasidagi chuqur muammosi endi 'Jarayonda' holatida",
    reportId: 'rep-001',
    read: false,
    createdAt: '2025-07-22T14:00:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    type: 'comment',
    title: "Sizning muammongizga izoh qo'shildi",
    message: "Malika Yusupova: Ha, men ham shu yo'ldan o'taman...",
    reportId: 'rep-001',
    read: false,
    createdAt: '2025-07-22T10:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-1',
    type: 'vote',
    title: 'Muammongiz yangi ovoz oldi',
    message: "Suv quvuri muammongiz 92 ovozga yetdi",
    reportId: 'rep-004',
    read: true,
    createdAt: '2025-07-17T12:00:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-1',
    type: 'completion',
    title: 'Muammo hal qilindi!',
    message: "Suv quvuri muammosi Toshkent Suvokova tomonidan hal qilindi",
    reportId: 'rep-004',
    read: true,
    createdAt: '2025-07-17T16:00:00Z',
  },
];

export const DAILY_STATS = [
  { date: '18 Iyul', count: 8, resolved: 3 },
  { date: '19 Iyul', count: 12, resolved: 5 },
  { date: '20 Iyul', count: 15, resolved: 7 },
  { date: '21 Iyul', count: 10, resolved: 4 },
  { date: '22 Iyul', count: 18, resolved: 9 },
  { date: '23 Iyul', count: 22, resolved: 6 },
  { date: 'Bugun', count: 14, resolved: 8 },
];

export const MONTHLY_STATS = [
  { month: 'Yanvar', count: 145, resolved: 120 },
  { month: 'Fevral', count: 132, resolved: 118 },
  { month: 'Mart', count: 178, resolved: 155 },
  { month: 'Aprel', count: 156, resolved: 142 },
  { month: 'May', count: 203, resolved: 187 },
  { month: 'Iyun', count: 234, resolved: 210 },
  { month: 'Iyul', count: 189, resolved: 156 },
];

export const MOCK_ANNOUNCEMENTS: MapAnnouncement[] = [
  {
    id: 'ann-001',
    organizationId: 'org-roads',
    organizationName: "Toshkent Yo'l Boshqarmasi",
    type: 'road_closure',
    title: "Amir Temur xiyoboni yo'li yopilgan",
    description: "Ko'prik ta'mirlash ishlari tufayli Amir Temur xiyobonining markaziy qismi 10 kun davomida yopiladi. Haydovchilardan muqobil yo'ldan foydalanish so'raladi.",
    route: [
      [41.300, 69.270],
      [41.297, 69.275],
      [41.294, 69.280],
    ],
    alternativeRoute: [
      [41.300, 69.270],
      [41.303, 69.273],
      [41.301, 69.280],
      [41.294, 69.280],
    ],
    alternativeDescription: "Navoiy ko'chasi orqali aylanib o'ting",
    startDate: '2025-07-22T08:00:00Z',
    endDate: '2025-08-01T18:00:00Z',
    status: 'active',
    createdAt: '2025-07-21T14:00:00Z',
  },
  {
    id: 'ann-002',
    organizationId: 'org-electricity',
    organizationName: "Toshkent Elektr Tarmog'i",
    type: 'electricity_cutoff',
    title: "Chilonzor 14-kvartaldagi elektr ta'minoti to'xtatiladi",
    description: "Transformator almashtirish ishlari munosabati bilan 25-iyul kuni soat 09:00 dan 17:00 gacha elektr ta'minoti to'xtatiladi.",
    route: [
      [41.279, 69.198],
      [41.282, 69.201],
      [41.280, 69.205],
      [41.277, 69.203],
      [41.279, 69.198],
    ],
    startDate: '2025-07-25T09:00:00Z',
    endDate: '2025-07-25T17:00:00Z',
    status: 'planned',
    createdAt: '2025-07-23T10:00:00Z',
  },
  {
    id: 'ann-003',
    organizationId: 'org-water',
    organizationName: 'Toshkent Suvokova',
    type: 'water_cutoff',
    title: "Yunusobod tumani: Suv ta'minoti vaqtincha to'xtatiladi",
    description: "Asosiy magistral quvur ta'mirlash ishlari tufayli 24-iyul kuni soat 08:00 dan 16:00 gacha suv ta'minoti to'xtatiladi. Saqlash uchun suv zaxira qilib qo'yishingizni so'raymiz.",
    route: [
      [41.350, 69.288],
      [41.345, 69.293],
      [41.340, 69.290],
    ],
    startDate: '2025-07-24T08:00:00Z',
    endDate: '2025-07-24T16:00:00Z',
    status: 'active',
    createdAt: '2025-07-23T08:00:00Z',
  },
  {
    id: 'ann-004',
    organizationId: 'org-roads',
    organizationName: "Toshkent Yo'l Boshqarmasi",
    type: 'road_repair',
    title: "Mirzo Ulug'bek ko'chasi ta'miri",
    description: "Asfalt qoplama yangilanmoqda. Ta'mirlash vaqtida ikki tomonlama harakat bir tomonlama qilinadi.",
    route: [
      [41.320, 69.308],
      [41.315, 69.312],
      [41.310, 69.310],
    ],
    startDate: '2025-07-20T07:00:00Z',
    endDate: '2025-07-28T19:00:00Z',
    status: 'active',
    createdAt: '2025-07-19T16:00:00Z',
  },
];
