import { Category, CategoryId, RoutingRule } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'roads',
    name: "Yo'llar",
    nameEn: 'Roads',
    icon: '🛣️',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    organizationId: 'org-roads',
  },
  {
    id: 'electricity',
    name: 'Elektr',
    nameEn: 'Electricity',
    icon: '⚡',
    color: '#D97706',
    bgColor: '#FEF3C7',
    organizationId: 'org-electricity',
  },
  {
    id: 'water',
    name: 'Suv',
    nameEn: 'Water',
    icon: '💧',
    color: '#0EA5E9',
    bgColor: '#E0F2FE',
    organizationId: 'org-water',
  },
  {
    id: 'gas',
    name: 'Gaz',
    nameEn: 'Gas',
    icon: '🔥',
    color: '#EA580C',
    bgColor: '#FFF7ED',
    organizationId: 'org-gas',
  },
  {
    id: 'sewage',
    name: 'Kanalizatsiya',
    nameEn: 'Sewage',
    icon: '🪣',
    color: '#854D0E',
    bgColor: '#FEF9C3',
    organizationId: 'org-water',
  },
  {
    id: 'garbage',
    name: 'Axlat',
    nameEn: 'Garbage',
    icon: '🗑️',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    organizationId: 'org-sanitation',
  },
  {
    id: 'streetlights',
    name: "Ko'cha chiroqlari",
    nameEn: 'Street Lights',
    icon: '💡',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    organizationId: 'org-electricity',
  },
  {
    id: 'parks',
    name: 'Parklar',
    nameEn: 'Parks',
    icon: '🌳',
    color: '#15803D',
    bgColor: '#DCFCE7',
    organizationId: 'org-landscaping',
  },
  {
    id: 'trees',
    name: 'Daraxtlar',
    nameEn: 'Trees',
    icon: '🌲',
    color: '#166534',
    bgColor: '#F0FDF4',
    organizationId: 'org-landscaping',
  },
  {
    id: 'transport',
    name: 'Jamoat transporti',
    nameEn: 'Public Transport',
    icon: '🚌',
    color: '#1D4ED8',
    bgColor: '#EFF6FF',
    organizationId: 'org-transport',
  },
  {
    id: 'environment',
    name: 'Atrof-muhit',
    nameEn: 'Environment',
    icon: '🌿',
    color: '#15803D',
    bgColor: '#F0FDF4',
    organizationId: 'org-environment',
  },
  {
    id: 'buildings',
    name: 'Binolar',
    nameEn: 'Buildings',
    icon: '🏗️',
    color: '#475569',
    bgColor: '#F1F5F9',
    organizationId: 'org-construction',
  },
  {
    id: 'safety',
    name: 'Xavfsizlik',
    nameEn: 'Safety',
    icon: '🚨',
    color: '#DC2626',
    bgColor: '#FEF2F2',
    organizationId: 'org-police',
  },
  {
    id: 'animals',
    name: 'Hayvonlar',
    nameEn: 'Animals',
    icon: '🐕',
    color: '#92400E',
    bgColor: '#FEF3C7',
    organizationId: 'org-environment',
  },
  {
    id: 'other',
    name: 'Boshqalar',
    nameEn: 'Other',
    icon: '📋',
    color: '#6B7280',
    bgColor: '#F3F4F6',
    organizationId: 'org-admin',
  },
];

export const STATUS_CONFIG = {
  new: {
    label: 'Yangi',
    color: '#DC2626',
    bgColor: '#FEF2F2',
    borderColor: '#FECACA',
    markerColor: '#DC2626',
  },
  review: {
    label: "Ko'rib chiqilmoqda",
    color: '#EA580C',
    bgColor: '#FFF7ED',
    borderColor: '#FED7AA',
    markerColor: '#EA580C',
  },
  accepted: {
    label: 'Qabul qilindi',
    color: '#CA8A04',
    bgColor: '#FEFCE8',
    borderColor: '#FDE68A',
    markerColor: '#CA8A04',
  },
  inprogress: {
    label: 'Jarayonda',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    markerColor: '#2563EB',
  },
  completed: {
    label: 'Bajarildi',
    color: '#16A34A',
    bgColor: '#F0FDF4',
    borderColor: '#BBF7D0',
    markerColor: '#16A34A',
  },
  rejected: {
    label: 'Rad etildi',
    color: '#6B7280',
    bgColor: '#F3F4F6',
    borderColor: '#D1D5DB',
    markerColor: '#6B7280',
  },
  ignored: {
    label: "E'tiborga olinmadi",
    color: '#374151',
    bgColor: '#F9FAFB',
    borderColor: '#D1D5DB',
    markerColor: '#374151',
  },
};

export const PRIORITY_CONFIG = {
  low: { label: 'Past', color: '#6B7280', bgColor: '#F3F4F6' },
  medium: { label: "O'rta", color: '#D97706', bgColor: '#FEF3C7' },
  high: { label: 'Yuqori', color: '#EA580C', bgColor: '#FFF7ED' },
  urgent: { label: 'Shoshilinch', color: '#DC2626', bgColor: '#FEF2F2' },
};

export const DEFAULT_ROUTING_RULES: RoutingRule[] = [
  { categoryId: 'roads', organizationId: 'org-roads', organizationName: "Yo'l Boshqarmasi" },
  { categoryId: 'electricity', organizationId: 'org-electricity', organizationName: 'Elektr Tarmog\'i' },
  { categoryId: 'water', organizationId: 'org-water', organizationName: 'Suvokova' },
  { categoryId: 'gas', organizationId: 'org-gas', organizationName: 'Toshkentgaz' },
  { categoryId: 'sewage', organizationId: 'org-water', organizationName: 'Suvokova' },
  { categoryId: 'garbage', organizationId: 'org-sanitation', organizationName: 'Sanitariya Xizmati' },
  { categoryId: 'streetlights', organizationId: 'org-electricity', organizationName: 'Elektr Tarmog\'i' },
  { categoryId: 'parks', organizationId: 'org-landscaping', organizationName: 'Obodonlashtirish' },
  { categoryId: 'trees', organizationId: 'org-landscaping', organizationName: 'Obodonlashtirish' },
  { categoryId: 'transport', organizationId: 'org-transport', organizationName: 'Shahar Transport' },
  { categoryId: 'environment', organizationId: 'org-environment', organizationName: 'Ekologiya' },
  { categoryId: 'buildings', organizationId: 'org-construction', organizationName: 'Shaharsozlik' },
  { categoryId: 'safety', organizationId: 'org-police', organizationName: 'Ichki Ishlar' },
  { categoryId: 'animals', organizationId: 'org-environment', organizationName: 'Ekologiya' },
  { categoryId: 'other', organizationId: 'org-admin', organizationName: "Shahar Ma'muriyati" },
];

export const ANNOUNCEMENT_TYPE_CONFIG: Record<string, { label: string; color: string; bgColor: string; lineColor: string; icon: string }> = {
  road_closure: { label: "Yo'l yopiq", color: '#DC2626', bgColor: '#FEF2F2', lineColor: '#DC2626', icon: '🚧' },
  road_repair: { label: "Ta'mirlash", color: '#EA580C', bgColor: '#FFF7ED', lineColor: '#F97316', icon: '🔨' },
  road_diversion: { label: 'Muqobil yo\'l', color: '#2563EB', bgColor: '#EFF6FF', lineColor: '#3B82F6', icon: '↪️' },
  water_cutoff: { label: 'Suv to\'xtatiladi', color: '#0EA5E9', bgColor: '#E0F2FE', lineColor: '#0EA5E9', icon: '💧' },
  electricity_cutoff: { label: 'Elektr to\'xtatiladi', color: '#D97706', bgColor: '#FEF3C7', lineColor: '#F59E0B', icon: '⚡' },
  gas_cutoff: { label: 'Gaz to\'xtatiladi', color: '#EA580C', bgColor: '#FFF7ED', lineColor: '#FB923C', icon: '🔥' },
  event: { label: 'Tadbir', color: '#7C3AED', bgColor: '#EDE9FE', lineColor: '#8B5CF6', icon: '🎪' },
  other: { label: 'Boshqa', color: '#6B7280', bgColor: '#F3F4F6', lineColor: '#9CA3AF', icon: '📢' },
};

export const getCategoryById = (id: CategoryId): Category => {
  return CATEGORIES.find(c => c.id === id) || CATEGORIES[CATEGORIES.length - 1];
};
