import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MapPin, Upload, ArrowLeft, Check, Crosshair, AlertCircle, Loader2 } from 'lucide-react';
import { useAppStore } from '@/stores/appStore';
import { useAuth } from '@/hooks/useAuth';
import { CATEGORIES } from '@/constants/categories';
import { CategoryId, Priority, Report } from '@/types';
import { cn } from '@/lib/utils';
import { supabase } from '@/lib/supabase';
import MapView from '@/components/features/map/MapView';

const DISTRICTS=['Yunusobod','Chilonzor',"Mirzo Ulug'bek",'Yakkasaroy','Shayxontohur','Olmazor','Sergeli','Uchtepa','Yashnobod','Bektemir'];
const STEPS=['Kategoriya','Joylashuv',"Ma'lumot",'Tasdiqlash'];

export default function CreateReportPage(){
  const {currentUser,openAuthModal}=useAuth(); const {addReport,reports,routingRules}=useAppStore(); const navigate=useNavigate();
  const [step,setStep]=useState(0); const [category,setCategory]=useState<CategoryId|null>(null);
  const [location,setLocation]=useState({lat:41.2995,lng:69.2401,address:'',district:''});
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [priority,setPriority]=useState<Priority>('medium');
  const [anonymous,setAnonymous]=useState(false); const [photos,setPhotos]=useState<string[]>([]); const [busy,setBusy]=useState(false); const [submitted,setSubmitted]=useState(false); const [createdId,setCreatedId]=useState('');
  const nearby=category?reports.find(r=>Math.abs(r.location.lat-location.lat)<.003&&Math.abs(r.location.lng-location.lng)<.003&&r.categoryId===category):null;
  if(!currentUser)return <div className="min-h-screen pt-16 flex items-center justify-center bg-gray-50"><div className="text-center bg-white rounded-2xl shadow-glass p-10 max-w-sm w-full mx-4"><div className="text-5xl mb-4">🔒</div><h2 className="text-xl font-bold mb-2">Kirish talab qilinadi</h2><p className="text-sm text-gray-500 mb-6">Muammo bildirish uchun tizimga kiring</p><button onClick={()=>openAuthModal('login')} className="city-btn-primary w-full justify-center">Kirish</button></div></div>;
  const uploadPhotos=async(files:FileList|null)=>{if(!files||!supabase)return;const urls:string[]=[];for(const file of Array.from(files).slice(0,10)){if(!file.type.startsWith('image/'))continue;const ext=file.name.split('.').pop()||'jpg';const path=`${currentUser.id}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('opencity-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const {data}=supabase.storage.from('opencity-media').getPublicUrl(path);urls.push(data.publicUrl);}setPhotos(p=>[...p,...urls]);};
  const gps=()=>navigator.geolocation?.getCurrentPosition(pos=>setLocation(l=>({...l,lat:pos.coords.latitude,lng:pos.coords.longitude})),()=>{});
  const submit=async()=>{if(!category||title.length<10||description.length<20)return;setBusy(true);try{const org=routingRules.find(r=>r.categoryId===category)?.organizationId||'';const draft:Report={id:'',title,description,categoryId:category,status:'new',location,photos,authorId:currentUser.id,authorName:currentUser.name,authorAvatar:currentUser.avatar,anonymous,organizationId:org,votes:0,isVoted:false,comments:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),timeline:[],priority,viewCount:0};const saved=await addReport(draft);if(!saved)throw new Error('Muammo saqlanmadi');setCreatedId(saved.id);setSubmitted(true);}catch(e:any){alert(e?.message||'Muammoni yuborishda xatolik yuz berdi');}finally{setBusy(false);}};
  if(submitted)return <div className="min-h-screen pt-16 flex items-center justify-center bg-gray-50"><div className="text-center bg-white rounded-2xl shadow-glass p-10 max-w-sm w-full mx-4"><div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4"><Check className="w-8 h-8 text-green-600"/></div><h2 className="text-xl font-bold mb-2">Muvaffaqiyatli yuborildi!</h2><p className="text-sm text-gray-500 mb-6">Muammo real bazaga saqlandi va mas'ul tashkilotga yuborildi.</p><button onClick={()=>navigate(`/reports/${createdId}`)} className="city-btn-primary w-full justify-center">Muammoni ko'rish</button></div></div>;
  const canNext=step===0?!!category:step===1?!!location.address&&!!location.district:step===2?title.length>=10&&description.length>=20:true;
  return <div className="min-h-screen pt-16 bg-gray-50"><div className="max-w-2xl mx-auto px-4 py-8"><div className="flex items-center gap-3 mb-8"><button onClick={()=>step?setStep(step-1):navigate(-1)} className="city-btn-ghost p-2 rounded-xl"><ArrowLeft className="w-5 h-5"/></button><div><h1 className="text-xl font-bold">Muammo bildirish</h1><p className="text-sm text-gray-500">{step+1}/{STEPS.length}: {STEPS[step]}</p></div></div><div className="flex gap-2 mb-8">{STEPS.map((s,i)=><div key={s} className="flex-1"><div className={cn('h-1.5 rounded-full',i<=step?'bg-[#2563EB]':'bg-gray-200')}/><p className="text-xs mt-1.5 text-center hidden sm:block">{s}</p></div>)}</div><div className="bg-white rounded-2xl shadow-glass border border-gray-100 p-6">
    {step===0&&<><h2 className="text-lg font-bold mb-1">Kategoriya tanlang</h2><p className="text-sm text-gray-500 mb-5">Muammo turiga mos kategoriyani belgilang</p><div className="grid grid-cols-3 gap-2.5">{CATEGORIES.map(c=><button key={c.id} onClick={()=>setCategory(c.id as CategoryId)} className={cn('p-3 rounded-xl border-2 text-center',category===c.id?'border-[#2563EB]':'border-gray-100')}><div className="text-2xl mb-1">{c.icon}</div><div className="text-xs font-semibold">{c.name}</div></button>)}</div>{category&&<div className="mt-4 p-3 bg-blue-50 rounded-xl flex gap-2"><AlertCircle className="w-4 h-4 text-blue-600 mt-0.5"/><p className="text-xs text-blue-700">Mas'ul: <b>{routingRules.find(r=>r.categoryId===category)?.organizationName||"Shahar Ma'muriyati"}</b></p></div>}</>}
    {step===1&&<><h2 className="text-lg font-bold mb-1">Joylashuvni belgilang</h2><p className="text-sm text-gray-500 mb-4">Manzil va tuman ma'lumotlarini kiriting</p><div className="h-56 rounded-xl overflow-hidden mb-4"><MapView reports={[]} center={[location.lat,location.lng]} zoom={13} height="100%"/></div><input value={location.address} onChange={e=>setLocation(l=>({...l,address:e.target.value}))} className="city-input mb-3" placeholder="Aniq manzil..."/><select value={location.district} onChange={e=>setLocation(l=>({...l,district:e.target.value}))} className="city-input mb-3"><option value="">Tumanni tanlang...</option>{DISTRICTS.map(d=><option key={d}>{d}</option>)}</select><button onClick={gps} className="city-btn-secondary w-full justify-center gap-2"><Crosshair className="w-4 h-4"/> GPS orqali aniqlash</button>{nearby&&<div className="mt-4 p-3 bg-amber-50 rounded-xl text-xs">⚠️ Shu hududda o‘xshash muammo bor: <b>{nearby.title}</b></div>}</>}
    {step===2&&<><h2 className="text-lg font-bold mb-1">Muammo haqida yozing</h2><p className="text-sm text-gray-500 mb-5">Batafsil ma'lumot tezroq hal qilishga yordam beradi</p><input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} className="city-input mb-3" placeholder="Sarlavha (kamida 10 belgi)"/><textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000} rows={6} className="city-input resize-none mb-4" placeholder="Muammoni batafsil tasvirlang (kamida 20 belgi)..."/><div className="grid grid-cols-4 gap-2 mb-4">{(['low','medium','high','urgent'] as Priority[]).map(p=><button key={p} onClick={()=>setPriority(p)} className={cn('py-2 rounded-xl border-2 text-xs',priority===p?'border-blue-600 bg-blue-50':'border-gray-200')}>{p==='low'?'Past':p==='medium'?"O'rta":p==='high'?'Yuqori':'Shoshilinch'}</button>)}</div><label className="block border-2 border-dashed rounded-xl p-5 text-center cursor-pointer"><Upload className="w-6 h-6 mx-auto mb-2 text-gray-400"/><span className="text-sm text-gray-500">Rasm tanlash</span><input type="file" accept="image/*" multiple hidden onChange={e=>uploadPhotos(e.target.files).catch(err=>alert(err.message))}/></label>{photos.length>0&&<p className="text-xs text-green-600 mt-2">{photos.length} ta rasm yuklandi</p>}<label className="flex items-center gap-3 mt-4"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/><span className="text-sm">Anonim yuborish</span></label></>}
    {step===3&&<><h2 className="text-lg font-bold mb-4">Tasdiqlash</h2><div className="space-y-2 text-sm bg-gray-50 rounded-xl p-4"><p><b>Kategoriya:</b> {category}</p><p><b>Sarlavha:</b> {title}</p><p><b>Manzil:</b> {location.address}, {location.district}</p><p><b>Rasmlar:</b> {photos.length}</p><p><b>Anonim:</b> {anonymous?'Ha':'Yo‘q'}</p></div></>}
    <div className="flex gap-3 mt-6">{step>0&&<button onClick={()=>setStep(step-1)} className="city-btn-secondary flex-1 justify-center">Orqaga</button>}{step<3?<button disabled={!canNext} onClick={()=>setStep(step+1)} className="city-btn-primary flex-1 justify-center disabled:opacity-40">Davom etish</button>:<button disabled={busy} onClick={submit} className="city-btn-primary flex-1 justify-center disabled:opacity-50">{busy?<><Loader2 className="w-4 h-4 animate-spin"/>Yuborilmoqda...</>:'Muammoni yuborish'}</button>}</div>
  </div></div></div>;
}
