import { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { ClipboardList, CheckCircle2, Clock, TrendingUp, Award, Users, ThumbsUp } from 'lucide-react';
import { AreaChart, Area, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import { useAppStore } from '@/stores/appStore';
import { STATUS_CONFIG, getCategoryById } from '@/constants/categories';
import StatsCard from '@/components/features/dashboard/StatsCard';
import ReportCard from '@/components/features/reports/ReportCard';
import { formatNumber } from '@/lib/utils';

const PIE_COLORS = ['#DC2626','#EA580C','#CA8A04','#2563EB','#16A34A','#6B7280','#374151'];

export default function DashboardPage() {
  const { reports, organizations } = useAppStore();
  const navigate = useNavigate();
  const stats = useMemo(() => ({ total: reports.length, completed: reports.filter(r => r.status === 'completed').length, pending: reports.filter(r => !['completed','rejected','ignored'].includes(r.status)).length, totalVotes: reports.reduce((s,r)=>s+r.votes,0) }), [reports]);
  const statusDist = useMemo(() => Object.entries(STATUS_CONFIG).map(([k,v],i)=>({name:v.label,value:reports.filter(r=>r.status===k).length,color:PIE_COLORS[i%PIE_COLORS.length]})).filter(x=>x.value>0),[reports]);
  const catStats = useMemo(() => { const c:Record<string,number>={}; reports.forEach(r=>c[r.categoryId]=(c[r.categoryId]||0)+1); return Object.entries(c).map(([id,count])=>({name:getCategoryById(id as any)?.name||id,count})).sort((a,b)=>b.count-a.count).slice(0,8); },[reports]);
  const dailyStats = useMemo(() => { const m=new Map<string,{date:string,count:number,resolved:number}>(); reports.forEach(r=>{const d=new Date(r.createdAt);if(isNaN(d.getTime()))return;const k=d.toISOString().slice(0,10);const x=m.get(k)||{date:k.slice(5),count:0,resolved:0};x.count++;if(r.status==='completed')x.resolved++;m.set(k,x)});return [...m.entries()].sort(([a],[b])=>a.localeCompare(b)).slice(-14).map(([,x])=>x); },[reports]);
  const monthlyStats = useMemo(() => { const m=new Map<string,{month:string,count:number,resolved:number}>(); reports.forEach(r=>{const d=new Date(r.createdAt);if(isNaN(d.getTime()))return;const k=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;const x=m.get(k)||{month:k,count:0,resolved:0};x.count++;if(r.status==='completed')x.resolved++;m.set(k,x)});return [...m.entries()].sort(([a],[b])=>a.localeCompare(b)).slice(-12).map(([,x])=>x); },[reports]);
  const topOrgs = useMemo(()=>[...organizations].sort((a,b)=>b.completedReports-a.completedReports).slice(0,5),[organizations]);
  const topReports = useMemo(()=>[...reports].sort((a,b)=>b.votes-a.votes).slice(0,3),[reports]);
  const solvedRate=stats.total?Math.round(stats.completed/stats.total*100):0;
  return <div className="min-h-screen pt-16 bg-gray-50">
    <div className="bg-gradient-to-r from-[#1D4ED8] to-[#2563EB] text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-6 sm:py-8"><h1 className="text-xl sm:text-2xl font-bold mb-1">OpenCity Dashboard</h1><p className="text-blue-100 text-sm">Real vaqt statistikasi va tahlillar</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-5">{[[stats.total,'Jami muammolar','📋'],[stats.completed,'Hal qilindi','✅'],[stats.pending,"Ko'rib chiqilmoqda",'⏳'],[`${solvedRate}%`,'Hal etish darajasi','📊']].map(([v,l,i])=><div key={l as string} className="bg-white/15 backdrop-blur-sm rounded-xl p-3 sm:p-4"><p className="text-xl sm:text-2xl">{i}</p><p className="text-xl sm:text-2xl font-bold">{formatNumber(v as any)}</p><p className="text-blue-100 text-xs">{l}</p></div>)}</div></div></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-5 sm:py-6 space-y-4 sm:space-y-6">
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4"><StatsCard title="Jami muammolar" value={formatNumber(stats.total)} icon={ClipboardList} color="blue" subtitle="Barcha vaqt"/><StatsCard title="Bajarildi" value={formatNumber(stats.completed)} icon={CheckCircle2} color="green" subtitle={`${solvedRate}% hal etish darajasi`}/><StatsCard title="Jarayonda" value={formatNumber(stats.pending)} icon={Clock} color="orange" subtitle="Aktiv muammolar"/><StatsCard title="Jami ovozlar" value={formatNumber(stats.totalVotes)} icon={ThumbsUp} color="purple" subtitle="Fuqarolar ishtiroki"/></div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 sm:gap-6"><div className="lg:col-span-2 bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2"><TrendingUp className="w-5 h-5 text-[#2563EB]"/>Haftalik dinamika</h2><ResponsiveContainer width="100%" height={200}><AreaChart data={dailyStats}><CartesianGrid strokeDasharray="3 3" stroke="#F1F5F9"/><XAxis dataKey="date" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Legend/><Area type="monotone" dataKey="count" stroke="#2563EB" fill="#EFF6FF" name="Yangi"/><Area type="monotone" dataKey="resolved" stroke="#16A34A" fill="#F0FDF4" name="Hal qilindi"/></AreaChart></ResponsiveContainer></div><div className="bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold text-gray-900 mb-3">Holat bo'yicha</h2><ResponsiveContainer width="100%" height={160}><PieChart><Pie data={statusDist} innerRadius={45} outerRadius={68} dataKey="value" paddingAngle={3}>{statusDist.map((x,i)=><Cell key={i} fill={x.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>{statusDist.map(x=><div key={x.name} className="flex justify-between text-xs py-1"><span>{x.name}</span><b>{x.value}</b></div>)}</div></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6"><div className="bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold mb-3">Kategoriyalar bo'yicha</h2><ResponsiveContainer width="100%" height={220}><BarChart data={catStats} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="name" width={90} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="count" fill="#2563EB" radius={[0,6,6,0]} name="Muammolar"/></BarChart></ResponsiveContainer></div><div className="bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold mb-3">Oylik statistika</h2><ResponsiveContainer width="100%" height={220}><AreaChart data={monthlyStats}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:10}}/><Tooltip/><Area type="monotone" dataKey="count" stroke="#7C3AED" fill="#EDE9FE" name="Jami"/><Area type="monotone" dataKey="resolved" stroke="#16A34A" fill="#F0FDF4" name="Hal qilindi"/></AreaChart></ResponsiveContainer></div></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6"><div className="bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold mb-4 flex items-center gap-2"><Award className="w-5 h-5 text-[#2563EB]"/>Eng faol tashkilotlar</h2>{topOrgs.map((o,i)=><button key={o.id} onClick={()=>navigate(`/organizations/${o.id}`)} className="w-full flex items-center gap-3 p-3 rounded-xl hover:bg-gray-50 text-left"><b className="w-6">#{i+1}</b><div className="flex-1 min-w-0"><p className="font-semibold truncate">{o.name}</p><p className="text-xs text-gray-400">✅ {o.completedReports} · ⭐ {o.rating||'—'}</p></div></button>)}</div><div className="bg-white rounded-2xl border border-gray-100 shadow-glass p-4 sm:p-6"><h2 className="font-bold mb-4 flex items-center gap-2"><Users className="w-5 h-5 text-[#2563EB]"/>Eng ko'p ovoz olgan</h2>{topReports.map(r=><ReportCard key={r.id} report={r} compact/>)}</div></div>
    </div></div>;
}
