import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Building2, ShieldCheck, AlertCircle, RefreshCw } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/hooks/useAuth';
import { useAppStore } from '@/stores/appStore';
import { cn } from '@/lib/utils';

export default function OrganizationDashboardPage(){
 const {currentUser,isOrganization,isAuthenticated}=useAuth(); const {organizations,reports,refresh}=useAppStore(); const navigate=useNavigate(); const [orgId,setOrgId]=useState(''); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{if(!supabase||!currentUser||!isOrganization){if(live)setLoading(false);return;}const {data}=await supabase.from('profiles').select('organization_id').eq('id',currentUser.id).maybeSingle();if(live){setOrgId(data?.organization_id||'');setLoading(false);}})();return()=>{live=false}},[currentUser,isOrganization]);
 useEffect(()=>{if(orgId)void refresh()},[orgId,refresh]);
 if(!isAuthenticated)return <Gate title="Tashkilot kabineti" text="Avval tizimga kiring." action={()=>navigate('/')} />;
 if(!isOrganization)return <Gate title="Ruxsat yo‘q" text="Bu bo‘lim faqat tasdiqlangan tashkilot xodimlari uchun." action={()=>navigate('/')} />;
 if(loading)return <div className="min-h-screen pt-16 flex items-center justify-center"><RefreshCw className="w-7 h-7 text-blue-600 animate-spin"/></div>;
 if(!orgId)return <Gate title="Tashkilot biriktirilmagan" text="Admin profilingizga tashkilot biriktirgandan keyin kabinet ochiladi." action={()=>navigate('/profile')} />;
 const org=organizations.find(o=>o.id===orgId); const own=reports.filter(r=>r.organizationId===orgId); const newCount=own.filter(r=>r.status==='new').length; const active=own.filter(r=>['review','accepted','inprogress'].includes(r.status)).length; const done=own.filter(r=>r.status==='completed').length;
 return <div className="min-h-screen pt-16 bg-slate-950 text-white"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><div className="glass-panel p-6 sm:p-8 mb-6"><div className="flex flex-col sm:flex-row sm:items-center gap-5"><div className="w-16 h-16 rounded-2xl bg-blue-500/15 border border-blue-400/20 flex items-center justify-center"><Building2 className="w-8 h-8 text-blue-400"/></div><div className="flex-1"><div className="flex items-center gap-2"><h1 className="text-2xl font-black">{org?.name||'Tashkilot kabineti'}</h1><ShieldCheck className="w-5 h-5 text-emerald-400"/></div><p className="text-slate-400 mt-1">{org?.district||currentUser.district||'Hudud'} · {currentUser.name}</p></div><button onClick={()=>navigate(`/organizations/${orgId}`)} className="city-btn-primary">Tashkilot profilini ochish</button></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">{[[newCount,'Yangi'],[active,'Jarayonda'],[done,'Bajarildi'],[own.length,'Jami']].map(([n,l])=><div key={l as string} className="glass-card p-5"><div className="text-3xl font-black">{n}</div><div className="text-sm text-slate-400 mt-1">{l}</div></div>)}</div><div className="glass-panel overflow-hidden"><div className="p-5 border-b border-white/10"><h2 className="font-bold text-lg">Murojaatlar</h2><p className="text-sm text-slate-400">Faqat sizga biriktirilgan tashkilot murojaatlari</p></div>{own.length===0?<div className="p-12 text-center text-slate-400">Hozircha murojaatlar yo‘q.</div>:own.slice(0,30).map(r=><button key={r.id} onClick={()=>navigate(`/organizations/${orgId}`)} className="w-full text-left p-4 border-b border-white/5 hover:bg-white/5 transition-colors"><div className="flex items-center gap-3"><span className={cn('w-2.5 h-2.5 rounded-full',r.priority==='urgent'?'bg-red-500 animate-pulse':r.status==='completed'?'bg-emerald-500':'bg-blue-500')}/><div className="flex-1 min-w-0"><p className="font-semibold truncate">{r.title}</p><p className="text-xs text-slate-400 truncate">📍 {r.location.address||r.location.district||'Manzil aniqlanmagan'}</p></div><span className="text-xs px-2 py-1 rounded-lg bg-white/10">{r.status}</span></div></button>)}</div><div className="mt-5 flex gap-3 p-4 rounded-2xl border border-amber-400/20 bg-amber-400/5 text-sm text-amber-200"><AlertCircle className="w-5 h-5 flex-shrink-0"/> Tashkilot xodimining vakolati backend RLS bilan ham tekshiriladi.</div></div></div>;
}
function Gate({title,text,action}:{title:string;text:string;action:()=>void}){return <div className="min-h-screen pt-16 flex items-center justify-center bg-slate-950 px-4"><div className="glass-panel p-8 text-center max-w-md w-full"><Building2 className="w-10 h-10 text-blue-400 mx-auto mb-4"/><h1 className="text-xl font-bold">{title}</h1><p className="text-slate-400 text-sm mt-2 mb-6">{text}</p><button onClick={action} className="city-btn-primary w-full">Davom etish</button></div></div>}
